mnist:
  data:
    dataset_name: mnist
    shape:
      - 1
      - 28
      - 28
  discriminator:
    network: basic_mnist_d_network
    train_op: basic_mnist_d_train_op
    saving_path: models/basic_mnist_discriminator.ckpt
    setup:
      internal_size: 2
      frame_size: 1
      n_fragments_per_image: 7
    training:
      num_epochs: 10
      batch_size: 64
      learning_rate: 0.0001
      beta_one: 0.5
  generator:
    network: basic_mnist_g_network
    train_op: basic_mnist_g_train_op
    saving_path: models/basic_mnist_generator.ckpt
    setup:
      z_dim: 20
      num_batches: 1000
      n_fragments_per_image: 5
    training:
      num_epochs: 10
      batch_size: 64
      learning_rate: 0.0001
      beta_one: 0.5
