mnist:
  data:
    dataset_name: mnist
    shape:
      - 1
      - 28
      - 28
  setup:
    n_fragments_per_image: 5
    internal_size: 3
    frame_size: 1
  discriminator:
    model_fn: basic_mnist_discriminator
    model_dir: models/basic_mnist_discriminator
  discriminator_training:
    num_epochs: 10
    batch_size: 64
    learning_rate: 0.001
    beta_one: 0.5
